spring:
  datasource:
    url: jdbc:h2:mem:cervejaria
    #url: jdbc:h2:file:cervejaria
    username: sa
    #password: 123456
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
server:
  port: 8091