INSERT INTO MARCAS(nome,pais,email,data_fundacao)
    VALUES ( 'Paulaner', 'Alemanha', 'paulaner@cervejas.de', '1886-02-15' );

INSERT INTO MARCAS(nome,pais,email,data_fundacao)
    VALUES ( 'Delirium', 'Belgica', 'delirium@cervejas.be', '1753-02-15');

INSERT INTO ESTILO (nome) VALUES ('Pilsner');
INSERT INTO ESTILO (nome) VALUES ('Stout');
INSERT INTO ESTILO (nome) VALUES ('Porter');


INSERT INTO LUPULO(nome,descricao) VALUES ( 'Ahtanum', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec enim diam vulputate ut. Nisi quis eleifend quam adipiscing vitae. Neque convallis a cras semper auctor neque vitae. Sit amet aliquam id diam maecenas ultricies mi eget. Lacus vestibulum sed arcu non odio euismod lacinia at quis. Adipiscing bibendum est ultricies integer quis auctor elit sed. Orci phasellus egestas tellus rutrum tellus. Turpis egestas integer eget aliquet nibh praesent tristique. Mattis rhoncus urna neque viverra justo nec.' );
INSERT INTO LUPULO(nome,descricao) VALUES ( 'Amarillo', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec enim diam vulputate ut. Nisi quis eleifend quam adipiscing vitae. Neque convallis a cras semper auctor neque vitae. Sit amet aliquam id diam maecenas ultricies mi eget. Lacus vestibulum sed arcu non odio euismod lacinia at quis. Adipiscing bibendum est ultricies integer quis auctor elit sed. Orci phasellus egestas tellus rutrum tellus. Turpis egestas integer eget aliquet nibh praesent tristique. Mattis rhoncus urna neque viverra justo nec.' );
INSERT INTO LUPULO(nome,descricao) VALUES ( 'Bitter Gold' , 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec enim diam vulputate ut. Nisi quis eleifend quam adipiscing vitae. Neque convallis a cras semper auctor neque vitae. Sit amet aliquam id diam maecenas ultricies mi eget. Lacus vestibulum sed arcu non odio euismod lacinia at quis. Adipiscing bibendum est ultricies integer quis auctor elit sed. Orci phasellus egestas tellus rutrum tellus. Turpis egestas integer eget aliquet nibh praesent tristique. Mattis rhoncus urna neque viverra justo nec.');
INSERT INTO LUPULO(nome,descricao) VALUES (  'Horizon', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec enim diam vulputate ut. Nisi quis eleifend quam adipiscing vitae. Neque convallis a cras semper auctor neque vitae. Sit amet aliquam id diam maecenas ultricies mi eget. Lacus vestibulum sed arcu non odio euismod lacinia at quis. Adipiscing bibendum est ultricies integer quis auctor elit sed. Orci phasellus egestas tellus rutrum tellus. Turpis egestas integer eget aliquet nibh praesent tristique. Mattis rhoncus urna neque viverra justo nec.' );
INSERT INTO LUPULO(nome,descricao) VALUES ( '335 - British Ale II' , 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec enim diam vulputate ut. Nisi quis eleifend quam adipiscing vitae. Neque convallis a cras semper auctor neque vitae. Sit amet aliquam id diam maecenas ultricies mi eget. Lacus vestibulum sed arcu non odio euismod lacinia at quis. Adipiscing bibendum est ultricies integer quis auctor elit sed. Orci phasellus egestas tellus rutrum tellus. Turpis egestas integer eget aliquet nibh praesent tristique. Mattis rhoncus urna neque viverra justo nec.');
INSERT INTO LUPULO(nome,descricao) VALUES ( '1469 - West Yorkshire Ale' , 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec enim diam vulputate ut. Nisi quis eleifend quam adipiscing vitae. Neque convallis a cras semper auctor neque vitae. Sit amet aliquam id diam maecenas ultricies mi eget. Lacus vestibulum sed arcu non odio euismod lacinia at quis. Adipiscing bibendum est ultricies integer quis auctor elit sed. Orci phasellus egestas tellus rutrum tellus. Turpis egestas integer eget aliquet nibh praesent tristique. Mattis rhoncus urna neque viverra justo nec.');
INSERT INTO LUPULO(nome,descricao) VALUES ( 'Chelan' , 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec enim diam vulputate ut. Nisi quis eleifend quam adipiscing vitae. Neque convallis a cras semper auctor neque vitae. Sit amet aliquam id diam maecenas ultricies mi eget. Lacus vestibulum sed arcu non odio euismod lacinia at quis. Adipiscing bibendum est ultricies integer quis auctor elit sed. Orci phasellus egestas tellus rutrum tellus. Turpis egestas integer eget aliquet nibh praesent tristique. Mattis rhoncus urna neque viverra justo nec.');
INSERT INTO LUPULO(nome,descricao) VALUES ( 'Sorachi Ace', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec enim diam vulputate ut. Nisi quis eleifend quam adipiscing vitae. Neque convallis a cras semper auctor neque vitae. Sit amet aliquam id diam maecenas ultricies mi eget. Lacus vestibulum sed arcu non odio euismod lacinia at quis. Adipiscing bibendum est ultricies integer quis auctor elit sed. Orci phasellus egestas tellus rutrum tellus. Turpis egestas integer eget aliquet nibh praesent tristique. Mattis rhoncus urna neque viverra justo nec.' );
INSERT INTO LUPULO(nome,descricao) VALUES ( 'Yakima Gol', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec enim diam vulputate ut. Nisi quis eleifend quam adipiscing vitae. Neque convallis a cras semper auctor neque vitae. Sit amet aliquam id diam maecenas ultricies mi eget. Lacus vestibulum sed arcu non odio euismod lacinia at quis. Adipiscing bibendum est ultricies integer quis auctor elit sed. Orci phasellus egestas tellus rutrum tellus. Turpis egestas integer eget aliquet nibh praesent tristique. Mattis rhoncus urna neque viverra justo nec.' );
INSERT INTO LUPULO(nome,descricao) VALUES ( '2633 - Octoberfest Lager Blend' , 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec enim diam vulputate ut. Nisi quis eleifend quam adipiscing vitae. Neque convallis a cras semper auctor neque vitae. Sit amet aliquam id diam maecenas ultricies mi eget. Lacus vestibulum sed arcu non odio euismod lacinia at quis. Adipiscing bibendum est ultricies integer quis auctor elit sed. Orci phasellus egestas tellus rutrum tellus. Turpis egestas integer eget aliquet nibh praesent tristique. Mattis rhoncus urna neque viverra justo nec.');
INSERT INTO LUPULO(nome,descricao) VALUES ( 'TriplePearl', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec enim diam vulputate ut. Nisi quis eleifend quam adipiscing vitae. Neque convallis a cras semper auctor neque vitae. Sit amet aliquam id diam maecenas ultricies mi eget. Lacus vestibulum sed arcu non odio euismod lacinia at quis. Adipiscing bibendum est ultricies integer quis auctor elit sed. Orci phasellus egestas tellus rutrum tellus. Turpis egestas integer eget aliquet nibh praesent tristique. Mattis rhoncus urna neque viverra justo nec.' );
INSERT INTO LUPULO(nome,descricao) VALUES ( 'Perle' , 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec enim diam vulputate ut. Nisi quis eleifend quam adipiscing vitae. Neque convallis a cras semper auctor neque vitae. Sit amet aliquam id diam maecenas ultricies mi eget. Lacus vestibulum sed arcu non odio euismod lacinia at quis. Adipiscing bibendum est ultricies integer quis auctor elit sed. Orci phasellus egestas tellus rutrum tellus. Turpis egestas integer eget aliquet nibh praesent tristique. Mattis rhoncus urna neque viverra justo nec.');
INSERT INTO LUPULO(nome,descricao) VALUES ( 'Saaz', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec enim diam vulputate ut. Nisi quis eleifend quam adipiscing vitae. Neque convallis a cras semper auctor neque vitae. Sit amet aliquam id diam maecenas ultricies mi eget. Lacus vestibulum sed arcu non odio euismod lacinia at quis. Adipiscing bibendum est ultricies integer quis auctor elit sed. Orci phasellus egestas tellus rutrum tellus. Turpis egestas integer eget aliquet nibh praesent tristique. Mattis rhoncus urna neque viverra justo nec.' );
INSERT INTO LUPULO(nome,descricao) VALUES ( 'Citra', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec enim diam vulputate ut. Nisi quis eleifend quam adipiscing vitae. Neque convallis a cras semper auctor neque vitae. Sit amet aliquam id diam maecenas ultricies mi eget. Lacus vestibulum sed arcu non odio euismod lacinia at quis. Adipiscing bibendum est ultricies integer quis auctor elit sed. Orci phasellus egestas tellus rutrum tellus. Turpis egestas integer eget aliquet nibh praesent tristique. Mattis rhoncus urna neque viverra justo nec.' );
INSERT INTO LUPULO(nome,descricao) VALUES ( 'Olympic', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec enim diam vulputate ut. Nisi quis eleifend quam adipiscing vitae. Neque convallis a cras semper auctor neque vitae. Sit amet aliquam id diam maecenas ultricies mi eget. Lacus vestibulum sed arcu non odio euismod lacinia at quis. Adipiscing bibendum est ultricies integer quis auctor elit sed. Orci phasellus egestas tellus rutrum tellus. Turpis egestas integer eget aliquet nibh praesent tristique. Mattis rhoncus urna neque viverra justo nec.' );
INSERT INTO LUPULO(nome,descricao) VALUES ( 'Chinook', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec enim diam vulputate ut. Nisi quis eleifend quam adipiscing vitae. Neque convallis a cras semper auctor neque vitae. Sit amet aliquam id diam maecenas ultricies mi eget. Lacus vestibulum sed arcu non odio euismod lacinia at quis. Adipiscing bibendum est ultricies integer quis auctor elit sed. Orci phasellus egestas tellus rutrum tellus. Turpis egestas integer eget aliquet nibh praesent tristique. Mattis rhoncus urna neque viverra justo nec.' );

INSERT INTO CERVEJA(nome,estilo_id,marca_id) VALUES ( 'Bourbon County Stout',2,1);
INSERT INTO CERVEJA(nome,estilo_id,marca_id) VALUES ( 'Founders Kentucky Breakfast',3,1);
INSERT INTO CERVEJA(nome,estilo_id,marca_id) VALUES ( 'Delirium Noctorum',2,2);
INSERT INTO CERVEJA(nome,estilo_id,marca_id) VALUES ( 'Chzevar',1,2);


INSERT INTO CERVEJA_LUPULOS VALUES ( 1, 1 );
INSERT INTO CERVEJA_LUPULOS VALUES ( 1, 3 );
INSERT INTO CERVEJA_LUPULOS VALUES ( 1, 5 );

INSERT INTO CERVEJA_LUPULOS VALUES ( 2, 3 );

INSERT INTO ROLE(nome) VALUES ( 'ADMIN' );
INSERT INTO ROLE(nome) VALUES ( 'USER' );

INSERT INTO USUARIO(email,nome,status,password) VALUES ( 'administrador@acme.com', 'Patolino',1 , '123456');
INSERT INTO USUARIO(email,nome,status,password) VALUES ( 'exfuncionario@acme.com', 'Eufrasino',2 , '123456');

INSERT INTO USUARIO_ROLES(ROLES_ID, USUARIO_ID) VALUES ( 1,1 );
INSERT INTO USUARIO_ROLES(ROLES_ID, USUARIO_ID) VALUES ( 2,1 );
INSERT INTO USUARIO_ROLES(ROLES_ID, USUARIO_ID) VALUES ( 2,2 );